void cgns_version
 (char[],
  char[],
  char[],
  char[]);

INT_ ug_io_read_cgns_grid
 (char[],
  char[],
  INT_,
  INT_ *,
  INT_ *,
  INT_ *,
  INT_ *,
  INT_ *,
  INT_ *,
  INT_ *,
  INT_ *,
  INT_ *,
  INT_1D *,
  INT_1D *,
  INT_4D *,
  INT_1D *,
  INT_3D *,
  INT_8D *,
  INT_1D *,
  INT_5D *,
  INT_6D *,
  INT_4D *,
  DOUBLE_3D *,
  DOUBLE_1D *,
  DOUBLE_1D *);

INT_ ug_io_write_cgns_grid
 (char[],
  char[],
  char[],
  INT_,
  INT_,
  INT_,
  INT_,
  INT_,
  INT_,
  INT_,
  INT_,
  INT_1D *,
  INT_1D *,
  INT_4D *,
  INT_1D *,
  INT_3D *,
  INT_8D *,
  INT_1D *,
  INT_5D *,
  INT_6D *,
  INT_4D *,
  DOUBLE_3D *,
  DOUBLE_1D *,
  DOUBLE_1D *);

INT_ ug_io_cgns_grid_lib_check (void);

void ug_io_cgns_register_read_grid
 (INT_ (*ext_routine) (char[],
                       char[],
                       INT_,
                       INT_ *,
                       INT_ *,
                       INT_ *,
                       INT_ *,
                       INT_ *,
                       INT_ *,
                       INT_ *,
                       INT_ *,
                       INT_ *,
                       INT_1D *,
                       INT_1D *,
                       INT_4D *,
                       INT_1D *,
                       INT_3D *,
                       INT_8D *,
                       INT_1D *,
                       INT_5D *,
                       INT_6D *,
                       INT_4D *,
                       DOUBLE_3D *,
                       DOUBLE_1D *,
                       DOUBLE_1D *));

void ug_io_cgns_register_write_grid
 (INT_ (*ext_routine) (char[],
                       char[],
                       char[],
                       INT_,
                       INT_,
                       INT_,
                       INT_,
                       INT_,
                       INT_,
                       INT_,
                       INT_,
                       INT_1D *,
                       INT_1D *,
                       INT_4D *,
                       INT_1D *,
                       INT_3D *,
                       INT_8D *,
                       INT_1D *,
                       INT_5D *,
                       INT_6D *,
                       INT_4D *,
                       DOUBLE_3D *,
                       DOUBLE_1D *,
                       DOUBLE_1D *));
