#include "UG_IO_LIB.h"

INT_ ug_io_write_mesh
 (FILE * Grid_File,
  char Error_Message[],
  INT_ Number_of_BL_Vol_Tets,
  INT_ Number_of_Nodes,
  INT_ Number_of_Surf_Quads,
  INT_ Number_of_Surf_Trias,
  INT_ Number_of_Vol_Hexs,
  INT_ Number_of_Vol_Pents_5,
  INT_ Number_of_Vol_Pents_6,
  INT_ Number_of_Vol_Tets,
  INT_1D * Surf_ID_Flag,
  INT_4D * Surf_Quad_Connectivity,
  INT_3D * Surf_Tria_Connectivity,
  INT_8D * Vol_Hex_Connectivity,
  INT_1D * Vol_ID_Flag,
  INT_5D * Vol_Pent_5_Connectivity,
  INT_6D * Vol_Pent_6_Connectivity,
  INT_4D * Vol_Tet_Connectivity,
  DOUBLE_3D * Coordinates)

{

/*
 * Write grid data to a MESH volume or surface grid file.
 * 
 * UG_IO LIB : Unstructured Grid - Input/Output Routine Library
 * $Id: ug_io_write_mesh.c,v 1.10 2012/08/23 04:01:49 marcum Exp $
 * Copyright 1994-2012, David L. Marcum
 */

  INT_ ID, Index, Write_Flag;

  Write_Flag = fprintf (Grid_File, "MeshVersionFormatted 2\n");
  Write_Flag = fprintf (Grid_File, "\n");
  Write_Flag = fprintf (Grid_File, "Dimension\n");
  Write_Flag = fprintf (Grid_File, "3\n");
  Write_Flag = fprintf (Grid_File, "\n");
  Write_Flag = fprintf (Grid_File, "#MESH FILE GENERATED BY UG_IO\n");

  Write_Flag = fprintf (Grid_File, "\n");
  Write_Flag = fprintf (Grid_File, "Vertices\n");
  Write_Flag = fprintf (Grid_File, "%i\n", Number_of_Nodes);

  for (Index = 1; Index <= Number_of_Nodes; ++Index)
  {
    Write_Flag = fprintf (Grid_File, "%.15g %.15g %.15g 0\n",
                          Coordinates[Index][0],
                          Coordinates[Index][1],
                          Coordinates[Index][2]);
  }

  if (Write_Flag < 0)
  {
    strcpy (Error_Message, "error writing MESH grid file");
    return (1);
  }

  if (Number_of_Surf_Trias > 0)
  {
    Write_Flag = fprintf (Grid_File, "\n");
    Write_Flag = fprintf (Grid_File, "Triangles\n");
    Write_Flag = fprintf (Grid_File, "%i\n", Number_of_Surf_Trias);

    for (Index = 1; Index <= Number_of_Surf_Trias; ++Index)
    {
      Write_Flag = fprintf (Grid_File, "%i %i %i %i\n",
                            Surf_Tria_Connectivity[Index][0],
                            Surf_Tria_Connectivity[Index][1],
                            Surf_Tria_Connectivity[Index][2],
                            Surf_ID_Flag[Index]);
    }

    if (Write_Flag < 0)
    {
      strcpy (Error_Message, "error writing MESH grid file");
      return (1);
    }
  }

  if (Number_of_Surf_Quads > 0)
  {
    Write_Flag = fprintf (Grid_File, "\n");
    Write_Flag = fprintf (Grid_File, "Quadrilaterals\n");
    Write_Flag = fprintf (Grid_File, "%i\n", Number_of_Surf_Quads);

    for (Index = 1; Index <= Number_of_Surf_Quads; ++Index)
    {
      Write_Flag = fprintf (Grid_File, "%i %i %i %i %i\n",
                            Surf_Quad_Connectivity[Index][0],
                            Surf_Quad_Connectivity[Index][1],
                            Surf_Quad_Connectivity[Index][2],
                            Surf_Quad_Connectivity[Index][3],
                            Surf_ID_Flag[Number_of_Surf_Trias+Index]);
    }

    if (Write_Flag < 0)
    {
      strcpy (Error_Message, "error writing MESH grid file");
      return (1);
    }
  }

  if (Number_of_Vol_Tets > 0)
  {
    Write_Flag = fprintf (Grid_File, "\n");
    Write_Flag = fprintf (Grid_File, "Tetrahedra\n");
    Write_Flag = fprintf (Grid_File, "%i\n", Number_of_Vol_Tets);

    for (Index = 1; Index <= Number_of_Vol_Tets; ++Index)
    {
      ID = (Vol_ID_Flag != NULL) ? Vol_ID_Flag[Index]:
           (Index <= Number_of_BL_Vol_Tets) ? 1: 0;

      Write_Flag = fprintf (Grid_File, "%i %i %i %i %i\n",
                            Vol_Tet_Connectivity[Index][0],
                            Vol_Tet_Connectivity[Index][1],
                            Vol_Tet_Connectivity[Index][2],
                            Vol_Tet_Connectivity[Index][3], ID);
    }

    if (Write_Flag < 0)
    {
      strcpy (Error_Message, "error writing MESH grid file");
      return (1);
    }
  }

  if (Number_of_Vol_Hexs > 0)
  {
    Write_Flag = fprintf (Grid_File, "\n");
    Write_Flag = fprintf (Grid_File, "Hexahedra\n");
    Write_Flag = fprintf (Grid_File, "%i\n", Number_of_Vol_Hexs);

    for (Index = 1; Index <= Number_of_Vol_Hexs; ++Index)
    {
      ID = (Vol_ID_Flag != NULL) ? Vol_ID_Flag[Number_of_Vol_Tets+Number_of_Vol_Pents_5+Number_of_Vol_Pents_6+Index]: 1;

      Write_Flag = fprintf (Grid_File, "%i %i %i %i %i %i %i %i %i\n",
                            Vol_Hex_Connectivity[Index][0],
                            Vol_Hex_Connectivity[Index][1],
                            Vol_Hex_Connectivity[Index][2],
                            Vol_Hex_Connectivity[Index][3],
                            Vol_Hex_Connectivity[Index][4],
                            Vol_Hex_Connectivity[Index][5],
                            Vol_Hex_Connectivity[Index][6],
                            Vol_Hex_Connectivity[Index][7], ID);
    }

    if (Write_Flag < 0)
    {
      strcpy (Error_Message, "error writing MESH grid file");
      return (1);
    }
  }

  if (Number_of_Vol_Pents_5 > 0)
  {
    Write_Flag = fprintf (Grid_File, "\n");
    Write_Flag = fprintf (Grid_File, "Pyramids\n");
    Write_Flag = fprintf (Grid_File, "%i\n", Number_of_Vol_Pents_5);

    for (Index = 1; Index <= Number_of_Vol_Pents_5; ++Index)
    {
      ID = (Vol_ID_Flag != NULL) ? Vol_ID_Flag[Number_of_Vol_Tets+Index]: 1;

      Write_Flag = fprintf (Grid_File, "%i %i %i %i %i %i\n",
                            Vol_Pent_5_Connectivity[Index][0],
                            Vol_Pent_5_Connectivity[Index][3],
                            Vol_Pent_5_Connectivity[Index][4],
                            Vol_Pent_5_Connectivity[Index][1],
                            Vol_Pent_5_Connectivity[Index][2], ID);
    }

    if (Write_Flag < 0)
    {
      strcpy (Error_Message, "error writing MESH grid file");
      return (1);
    }
  }

  if (Number_of_Vol_Pents_6 > 0)
  {
    Write_Flag = fprintf (Grid_File, "\n");
    Write_Flag = fprintf (Grid_File, "Prisms\n");
    Write_Flag = fprintf (Grid_File, "%i\n", Number_of_Vol_Pents_6);

    for (Index = 1; Index <= Number_of_Vol_Pents_6; ++Index)
    {
      ID = (Vol_ID_Flag != NULL) ? Vol_ID_Flag[Number_of_Vol_Tets+Number_of_Vol_Pents_5+Index]: 1;

      Write_Flag = fprintf (Grid_File, "%i %i %i %i %i %i %i\n",
                            Vol_Pent_6_Connectivity[Index][0],
                            Vol_Pent_6_Connectivity[Index][1],
                            Vol_Pent_6_Connectivity[Index][2],
                            Vol_Pent_6_Connectivity[Index][3],
                            Vol_Pent_6_Connectivity[Index][4],
                            Vol_Pent_6_Connectivity[Index][5], ID);
    }

    if (Write_Flag < 0)
    {
      strcpy (Error_Message, "error writing MESH grid file");
      return (1);
    }
  }

  Write_Flag = fprintf (Grid_File, "\n");
  Write_Flag = fprintf (Grid_File, "End\n");

  if (Write_Flag < 0)
  {
    strcpy (Error_Message, "error writing MESH grid file");
    return (1);
  }

  return (0);

}
