INT_ ug3_qtria_pyramid_check
 (INT_ mmsg,
  INT_ *nbface,
  INT_ nelemc5,
  INT_ *nnode,
  INT_ nquad,
  INT_1D * ibcibf,
  INT_1D * idibf,
  INT_1D * ierribf,
  INT_3D * inibf,
  INT_5D * inielc5,
  INT_4D * iniq,
  INT_1D * iqibf,
  INT_1D * irfibf,
  double cdfnqp,
  double tol,
  DOUBLE_1D * ds,
  DOUBLE_4D * trv,
  DOUBLE_3D * x);
