INT_ ug3_qtria_pyramid_create
 (INT_ mmsg,
  INT_ mquadp,
  INT_ *nbface,
  INT_ *nbfaced,
  INT_ *nelemc5,
  INT_ *nnode,
  INT_ *nnoded,
  INT_ *nquad,
  INT_ *nquadp,
  double cdfqp,
  INT_1D ** ibcibf_ptr,
  INT_1D ** idibf_ptr,
  INT_1D ** ierribf_ptr,
  INT_3D ** inibf_ptr,
  INT_5D ** inielc5_ptr,
  INT_4D ** iniq_ptr,
  INT_1D ** iqibf_ptr,
  INT_1D ** irfibf_ptr,
  DOUBLE_1D ** ds_ptr,
  DOUBLE_4D ** trv_ptr,
  DOUBLE_3D ** x_ptr);
