INT_ ug_chdir (const char path[]);
INT_ ug_chmod (const char *path, INT_ mode);
INT_ ug_execv (const char *path, char *const argv[]);
INT_ ug_fileno (FILE *stream);
INT_ ug_fstat (INT_ id, ug_stat_struct *buffer);
char *ug_getcwd (char *buffer, size_t size);
char *ug_getenv (const char *name);
INT_ ug_getpid (void);
INT_ ug_mkdir (const char *path, INT_ mode);
INT_ ug_pclose (FILE *stream);
FILE *ug_popen (const char *command, const char *mode);
INT_ ug_rmdir (const char *path);
INT_ ug_remove (const char *path);
INT_ ug_rename (const char *oldname, const char *newname);
INT_ ug_stat (const char *path, ug_stat_struct *buffer);
INT_ ug_system (const char *command);
void ug_srandom (unsigned seed);
long ug_random (void);
INT_ ug_unlink (const char *path);

char *ug_get_binary_file_mode (const char *mode);
char *ug_get_cwd (void);
INT_ ug_get_fullpath (const char *path, char *fullpath);
char *ug_get_home_dir (void);
char *ug_get_signal_message (INT_ signal);
void ug_get_sys_info (char machine_type[], char os_release[], char os_type[]);
char *ug_get_tmpdir (void);
FILE *ug_open_tmpdir (char *path);
void ug_register_signal_cleanup (void (*ext_signal_cleanup_routine) (void));
INT_ ug_remove_dir (const char *path);
INT_ ug_remove_file (const char *path);
INT_ ug_rename_file (const char *oldname, const char *newname);
void ug_signal (void);
void ug_signal_handler (int sig);
char *ug_signal_message (int sig);
void ug_splitpath (const char *path, char *drive, char *dname, char *fname, char *ext);
void ug_splitdir (char *dname, char *drive);
void ug_splitname (char *fname, char *ext);
